version: '3.8'
services:
  webapp:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_ADDR}
      - REDIS_DATABASES=${REDIS_DB}
    ports:
      - "6379:6379"
    volumes:
      - ./data:/root/redis
    
    
   
