// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int32
	Title       string
	Description pgtype.Text
	Completed   pgtype.Bool
	CreatedAt   pgtype.Timestamp
	UserID      int32
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
}
